### ISSUE TITLE
gradle task ':transformClassesWithDexForArmDebug' failed, java finished with non-zero exit value 2

### ISSUE THREAD

**Issue by xdegaye** [kuri65536/sl4a#22]
- android studio 1.5.1
- gradle 2.8
- oracle jdk version "1.8.0_74"

This error occurs often when building the APK with android studio and systematically when building the APK for the first time. Building with 'gradle assembleDebug' gives more details:

```
:transformClassesWithDexForArmDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/common/annotations/Beta;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-jdk/bin/java'' finished with non-zero exit value 2
```
- The com.google.common.annotations package is part of google guava libraries and the Common and Util subprojects are dependent on guava.
- Commenting the `compile files('libs/guava-r06.jar')` statement in the Common build script seems to fix the problem and the APK are built without error the first time now. This would be a regression in gradle since there is nothing wrong with the commented out statement.
- Anyway, as the Common subproject is dependent on Util, it seems that libs/guava-r06.jar would be better located in Util instead of in Common, so that Common does not depend directly on guava.

**Comment by xdegaye** [comment]
The google gradle android plugin documentation provides a tip to handle this case at [Handling transitive dependencies for local artifacts] (http://tools.android.com/tech-docs/new-build-system/tips#TOC-Handling-transitive-dependencies-for-local-artifacts-jars-and-aar-), and this solution works for me as well (creating a new gradle sub-project that contains the guava jar file).

**Comment by kuri65536** [comment]
Now I can build sl4a with newer android studio 2.2
